### ISSUE TITLE
Fails to start with message about OpenCL

### ISSUE THREAD

**Issue by yuvipanda** [conda-forge/qgis-feedstock#263] opened 2022-10-10 20:07 UTC
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

When I try to start qgis, it fails with the following info:

```
qgis: error while loading shared libraries: libOpenCL.so.1: cannot open shared object file: No such file or directory
```

### Installed packages

```shell
(notebook) jovyan@jupyter-yuvipanda:~$ conda list
# packages in environment at /srv/conda/envs/notebook:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                       1_gnu    conda-forge
aiohttp                   3.8.3                    pypi_0    pypi
aiosignal                 1.2.0                    pypi_0    pypi
alembic                   1.7.5              pyhd8ed1ab_0    conda-forge
alsa-lib                  1.2.7.2              h166bdaf_0    conda-forge
anyio                     3.4.0            py39hf3d152e_0    conda-forge
appmode                   0.8.0                    pypi_0    pypi
argon2-cffi               21.1.0           py39h3811e60_2    conda-forge
async-timeout             4.0.2                    pypi_0    pypi
async_generator           1.10                       py_0    conda-forge
attr                      2.5.1                h166bdaf_1    conda-forge
attrs                     21.2.0             pyhd8ed1ab_0    conda-forge
babel                     2.9.1              pyh44b312d_0    conda-forge
backcall                  0.2.0              pyh9f0ad1d_0    conda-forge
backports                 1.0                        py_2    conda-forge
backports.functools_lru_cache 1.6.4              pyhd8ed1ab_0    conda-forge
beautifulsoup4            4.11.1                   pypi_0    pypi
blas                      1.1                    openblas    conda-forge
bleach                    4.1.0              pyhd8ed1ab_0    conda-forge
blinker                   1.4                        py_1    conda-forge
blosc                     1.21.1               h83bc5f7_3    conda-forge
boost-cpp                 1.78.0               h75c5d50_1    conda-forge
brotlipy                  0.7.0           py39h3811e60_1003    conda-forge
bzip2                     1.0.8                h7f98852_4    conda-forge
c-ares                    1.18.1               h7f98852_0    conda-forge
ca-certificates           2021.10.8            ha878542_0    conda-forge
cachetools                5.2.0                    pypi_0    pypi
cairo                     1.16.0            ha61ee94_1014    conda-forge
certifi                   2021.10.8        py39hf3d152e_1    conda-forge
certipy                   0.1.3                      py_0    conda-forge
cffi                      1.15.0           py39h4bc2ebd_0    conda-forge
cfitsio                   4.1.0                hd9d235c_0    conda-forge
charset-normalizer        2.0.9              pyhd8ed1ab_0    conda-forge
click                     8.1.3                    pypi_0    pypi
contourpy                 1.0.5                    pypi_0    pypi
coverage                  6.5.0            py39hb9d737c_0    conda-forge
cryptography              36.0.1           py39h95dcef6_0    conda-forge
curl                      7.85.0               h7bff187_0    conda-forge
cycler                    0.11.0                   pypi_0    pypi
dbus                      1.13.18              hb2f20db_0    defaults
debugpy                   1.5.1            py39he80948d_0    conda-forge
decorator                 5.1.0              pyhd8ed1ab_0    conda-forge
defusedxml                0.7.1              pyhd8ed1ab_0    conda-forge
dill                      0.3.5.1                  pypi_0    pypi
draco                     1.5.3                h924138e_0    conda-forge
eigen                     3.4.0                h4bd325d_0    conda-forge
entrypoints               0.3             pyhd8ed1ab_1003    conda-forge
exiv2                     0.27.5               h848de5d_0    conda-forge
expat                     2.4.9                h27087fc_0    conda-forge
fastjsonschema            2.16.2                   pypi_0    pypi
fftw                      3.3.10          nompi_hf0379b8_105    conda-forge
font-ttf-dejavu-sans-mono 2.37                 hab24e00_0    conda-forge
font-ttf-inconsolata      3.000                h77eed37_0    conda-forge
font-ttf-source-code-pro  2.038                h77eed37_0    conda-forge
font-ttf-ubuntu           0.83                 hab24e00_0    conda-forge
fontconfig                2.14.0               hc2a2eb6_1    conda-forge
fonts-conda-ecosystem     1                             0    conda-forge
fonts-conda-forge         1                             0    conda-forge
fonttools                 4.37.4                   pypi_0    pypi
freetype                  2.12.1               hca18f0e_0    conda-forge
freexl                    1.0.6                h166bdaf_1    conda-forge
frozenlist                1.3.1                    pypi_0    pypi
future                    0.18.2           py39hf3d152e_5    conda-forge
gdal                      3.5.2            py39h92c1d47_1    conda-forge
geos                      3.11.0               h27087fc_0    conda-forge
geotiff                   1.7.1                h4fc65e6_3    conda-forge
gettext                   0.19.8.1          h27087fc_1009    conda-forge
giflib                    5.2.1                h516909a_2    conda-forge
git-credential-helpers    0.2                      pypi_0    pypi
github3-py                3.2.0                    pypi_0    pypi
glib                      2.74.0               h6239696_0    conda-forge
glib-tools                2.74.0               h6239696_0    conda-forge
google-api-core           2.10.2                   pypi_0    pypi
google-api-python-client  2.64.0                   pypi_0    pypi
google-auth               2.12.0                   pypi_0    pypi
google-auth-httplib2      0.1.0                    pypi_0    pypi
google-auth-oauthlib      0.5.3                    pypi_0    pypi
googleapis-common-protos  1.56.4                   pypi_0    pypi
greenlet                  1.1.2            py39he80948d_1    conda-forge
gsl                       2.7.1                h917eeb2_1    defaults
gspread                   5.6.0                    pypi_0    pypi
gst-plugins-base          1.20.3               h57caac4_2    conda-forge
gstreamer                 1.20.3               hd4edc92_2    conda-forge
hdf4                      4.2.15               h9772cbc_4    conda-forge
hdf5                      1.12.2          nompi_h2386368_100    conda-forge
httplib2                  0.20.4             pyhd8ed1ab_0    conda-forge
icu                       70.1                 h27087fc_0    conda-forge
idna                      3.1                pyhd3deb0d_0    conda-forge
importlib-metadata        4.10.0           py39hf3d152e_0    conda-forge
importlib_resources       5.4.0              pyhd8ed1ab_0    conda-forge
ipykernel                 6.6.0            py39hef51801_0    conda-forge
ipython                   7.30.1           py39hf3d152e_0    conda-forge
ipython_genutils          0.2.0                      py_1    conda-forge
ipywidgets                7.7.2                    pypi_0    pypi
jack                      1.9.18            h8c3723f_1003    conda-forge
jedi                      0.18.1           py39hf3d152e_0    conda-forge
jinja2                    3.0.3              pyhd8ed1ab_0    conda-forge
jpeg                      9e                   h166bdaf_2    conda-forge
json-c                    0.16                 hc379101_0    conda-forge
json5                     0.9.5              pyh9f0ad1d_0    conda-forge
jsonschema                4.3.2              pyhd8ed1ab_0    conda-forge
jupyter-contrib-core      0.4.0                    pypi_0    pypi
jupyter-contrib-nbextensions 0.5.1                    pypi_0    pypi
jupyter-desktop-server    0.1.3                    pypi_0    pypi
jupyter-highlight-selected-word 0.2.0                    pypi_0    pypi
jupyter-latex-envs        1.4.6                    pypi_0    pypi
jupyter-nbextensions-configurator 0.4.1                    pypi_0    pypi
jupyter-offlinenotebook   0.2.1              pyhd8ed1ab_0    conda-forge
jupyter-resource-usage    0.6.1              pyhd8ed1ab_0    conda-forge
jupyter-server            1.19.1                   pypi_0    pypi
jupyter-server-proxy      3.2.2                    pypi_0    pypi
jupyter-syncthing-proxy   1.0.3                    pypi_0    pypi
jupyter-tree-download     1.0.1                    pypi_0    pypi
jupyter_client            7.1.0              pyhd8ed1ab_0    conda-forge
jupyter_core              4.9.1            py39hf3d152e_1    conda-forge
jupyter_telemetry         0.1.0              pyhd8ed1ab_1    conda-forge
jupyterhub                2.3.1                    pypi_0    pypi
jupyterhub-singleuser     1.4.2            py39hf3d152e_0    conda-forge
jupyterlab                3.4.5                    pypi_0    pypi
jupyterlab_pygments       0.1.2              pyh9f0ad1d_0    conda-forge
jupyterlab_server         2.10.1             pyhd8ed1ab_0    conda-forge
jupyterlab_widgets        1.0.2              pyhd8ed1ab_0    conda-forge
kealib                    1.4.15               ha7026e8_1    conda-forge
keyutils                  1.6.1                h166bdaf_0    conda-forge
kiwisolver                1.4.4                    pypi_0    pypi
krb5                      1.19.3               h3790be6_0    conda-forge
laz-perf                  3.0.0                h4bd325d_0    conda-forge
lcms2                     2.12                 hddcbb42_0    conda-forge
ld_impl_linux-64          2.36.1               hea4e1c9_2    conda-forge
lerc                      4.0.0                h27087fc_0    conda-forge
libblas                   3.9.0           16_linux64_openblas    conda-forge
libcap                    2.65                 ha37c62d_0    conda-forge
libcblas                  3.9.0           16_linux64_openblas    conda-forge
libclang                  14.0.6          default_h2e3cab8_0    conda-forge
libclang13                14.0.6          default_h3a83d3e_0    conda-forge
libcups                   2.3.3                h3e49a29_2    conda-forge
libcurl                   7.85.0               h7bff187_0    conda-forge
libdap4                   3.20.6               hd7c4107_2    conda-forge
libdb                     6.2.32               he1b5a44_0    conda-forge
libdeflate                1.14                 h166bdaf_0    conda-forge
libedit                   3.1.20210910         h7f8727e_0    defaults
libev                     4.33                 h516909a_1    conda-forge
libevent                  2.1.10               h9b69904_4    conda-forge
libffi                    3.4.2                h7f98852_5    conda-forge
libflac                   1.3.4                h27087fc_0    conda-forge
libgcc-ng                 12.1.0              h8d9b700_16    conda-forge
libgdal                   3.5.2                hc23bfc3_1    conda-forge
libgfortran-ng            12.1.0              h69a702a_16    conda-forge
libgfortran5              12.1.0              hdcd56e2_16    conda-forge
libglib                   2.74.0               h7a41b64_0    conda-forge
libgomp                   12.1.0              h8d9b700_16    conda-forge
libiconv                  1.17                 h166bdaf_0    conda-forge
libkml                    1.3.0             h37653c0_1015    conda-forge
liblapack                 3.9.0           16_linux64_openblas    conda-forge
libllvm14                 14.0.6               he0ac6c6_0    conda-forge
libnetcdf                 4.8.1           nompi_h21705cb_104    conda-forge
libnghttp2                1.47.0               hdcd2b5c_1    conda-forge
libnsl                    2.0.0                h7f98852_0    conda-forge
libogg                    1.3.5                h27cfd23_1    defaults
libopenblas               0.3.21          pthreads_h78a6416_3    conda-forge
libopus                   1.3.1                h7f98852_1    conda-forge
libpng                    1.6.38               h753d276_0    conda-forge
libpq                     14.5                 hd77ab85_0    conda-forge
libprotobuf               3.21.7               h6239696_0    conda-forge
librttopo                 1.1.0               hf730bdb_11    conda-forge
libsndfile                1.0.31               h9c3ff4c_1    conda-forge
libsodium                 1.0.18               h36c2ea0_1    conda-forge
libspatialindex           1.9.3                h9c3ff4c_4    conda-forge
libspatialite             5.0.1               hd36657c_19    conda-forge
libsqlite                 3.39.4               h753d276_0    conda-forge
libssh2                   1.10.0               ha56f1ee_2    conda-forge
libstdcxx-ng              12.1.0              ha89aaad_16    conda-forge
libtiff                   4.4.0                h55922b4_4    conda-forge
libtool                   2.4.6             h9c3ff4c_1008    conda-forge
libudev1                  249                  h166bdaf_4    conda-forge
libuuid                   2.32.1            h7f98852_1000    conda-forge
libuv                     1.42.0               h7f98852_0    conda-forge
libvorbis                 1.3.7                he1b5a44_0    conda-forge
libwebp                   1.2.4                h522a892_0    conda-forge
libwebp-base              1.2.4                h166bdaf_0    conda-forge
libxcb                    1.13              h7f98852_1004    conda-forge
libxkbcommon              1.0.3                he3ba5ed_0    conda-forge
libxml2                   2.10.2               h4c7fe37_1    conda-forge
libxslt                   1.1.35               h8affb1d_0    conda-forge
libzip                    1.9.2                hc869a4a_1    conda-forge
libzlib                   1.2.12               h166bdaf_4    conda-forge
lxml                      4.9.1                    pypi_0    pypi
lz4-c                     1.9.3                h9c3ff4c_1    conda-forge
mako                      1.1.6              pyhd8ed1ab_0    conda-forge
markupsafe                2.0.1            py39h3811e60_1    conda-forge
matplotlib                3.6.1                    pypi_0    pypi
matplotlib-inline         0.1.3              pyhd8ed1ab_0    conda-forge
mistune                   2.0.4                    pypi_0    pypi
mock                      4.0.3            py39hf3d152e_3    conda-forge
multidict                 6.0.2                    pypi_0    pypi
mysql-common              8.0.30               haf5c9bc_1    conda-forge
mysql-libs                8.0.30               h28c427c_1    conda-forge
nbclassic                 0.3.4              pyhd8ed1ab_0    conda-forge
nbclient                  0.5.9              pyhd8ed1ab_0    conda-forge
nbconvert                 7.2.1                    pypi_0    pypi
nbformat                  5.7.0                    pypi_0    pypi
nbgitpuller               1.1.0                    pypi_0    pypi
ncurses                   6.3                  h27087fc_1    conda-forge
nest-asyncio              1.5.4              pyhd8ed1ab_0    conda-forge
nitro                     2.7.dev6             h27087fc_5    conda-forge
nodejs                    12.4.0               he1b5a44_0    conda-forge
nose2                     0.9.2                      py_0    conda-forge
notebook                  6.4.12                   pypi_0    pypi
nspr                      4.33                 h295c915_0    defaults
nss                       3.78                 h2350873_0    conda-forge
nteract_on_jupyter        2.1.3                      py_0    conda-forge
numpy                     1.23.3           py39hba7629e_0    conda-forge
oauthlib                  3.1.1              pyhd8ed1ab_0    conda-forge
openblas                  0.3.21          pthreads_h320a7e8_3    conda-forge
openjpeg                  2.5.0                h7d73246_1    conda-forge
openssl                   1.1.1q               h166bdaf_0    conda-forge
otter-grader              3.1.4                    pypi_0    pypi
owslib                    0.27.2             pyhd8ed1ab_1    conda-forge
packaging                 21.3               pyhd8ed1ab_0    conda-forge
pamela                    1.0.0                      py_0    conda-forge
pandas                    1.5.0                    pypi_0    pypi
pandoc                    2.16.2               h7f98852_0    conda-forge
pandocfilters             1.5.0              pyhd8ed1ab_0    conda-forge
parso                     0.8.3              pyhd8ed1ab_0    conda-forge
pcre                      8.45                 h9c3ff4c_0    conda-forge
pcre2                     10.37                hc3806b6_1    conda-forge
pdal                      2.4.3                hbecf0f4_1    conda-forge
pdfkit                    1.0.0                    pypi_0    pypi
pexpect                   4.8.0              pyh9f0ad1d_2    conda-forge
pickleshare               0.7.5                   py_1003    conda-forge
pillow                    9.2.0                    pypi_0    pypi
pip                       21.3.1             pyhd8ed1ab_0    conda-forge
pixman                    0.40.0               h36c2ea0_0    conda-forge
plotly                    5.10.0             pyhd8ed1ab_0    conda-forge
ply                       3.11                       py_1    conda-forge
poppler                   22.04.0              h0733791_3    conda-forge
poppler-data              0.4.11               hd8ed1ab_0    conda-forge
popularity-contest        0.4.1                    pypi_0    pypi
portaudio                 19.6.0               h8e90077_6    conda-forge
postgresql                14.5                 hfdbbde3_0    conda-forge
proj                      9.0.1                h93bde94_1    conda-forge
prometheus_client         0.12.0             pyhd8ed1ab_0    conda-forge
prompt-toolkit            3.0.24             pyha770c72_0    conda-forge
protobuf                  4.21.7                   pypi_0    pypi
psutil                    5.8.0            py39h3811e60_2    conda-forge
psycopg2                  2.9.3            py39h3811e60_0    conda-forge
pthread-stubs             0.4               h36c2ea0_1001    conda-forge
ptyprocess                0.7.0              pyhd3deb0d_0    conda-forge
pulseaudio                14.0                 h0868958_9    conda-forge
pyasn1                    0.4.8                    pypi_0    pypi
pyasn1-modules            0.2.8                    pypi_0    pypi
pycparser                 2.21               pyhd8ed1ab_0    conda-forge
pycurl                    7.44.1           py39h72e3413_1    conda-forge
pydantic                  1.10.2                   pypi_0    pypi
pygments                  2.10.0             pyhd8ed1ab_0    conda-forge
pyjwt                     2.3.0              pyhd8ed1ab_1    conda-forge
pyopenssl                 21.0.0             pyhd8ed1ab_0    conda-forge
pyparsing                 3.0.6              pyhd8ed1ab_0    conda-forge
pypdf2                    2.11.1                   pypi_0    pypi
pyproj                    3.4.0            py39hdcf6798_0    conda-forge
pyqt                      5.15.7           py39h18e9c17_0    conda-forge
pyqt5-sip                 12.11.0          py39h5a03fae_0    conda-forge
pyqtwebkit                5.15.7           py39h18e9c17_2    conda-forge
pyrsistent                0.18.0           py39h3811e60_0    conda-forge
pysocks                   1.7.1            py39hf3d152e_4    conda-forge
python                    3.9.13          h9a8a25e_0_cpython    conda-forge
python-dateutil           2.8.2              pyhd8ed1ab_0    conda-forge
python-json-logger        2.0.1              pyh9f0ad1d_0    conda-forge
python-on-whales          0.52.0                   pypi_0    pypi
python_abi                3.9                      2_cp39    conda-forge
pytz                      2021.3             pyhd8ed1ab_0    conda-forge
pyyaml                    6.0              py39hb9d737c_4    conda-forge
pyzmq                     22.3.0           py39h37b5a0c_1    conda-forge
qca                       2.3.4                h51e5271_0    conda-forge
qgis                      3.22.11          py39h3a22410_0    conda-forge
qjson                     0.9.0             h51e5271_1007    conda-forge
qscintilla2               2.13.3           py39h18e9c17_2    conda-forge
qt-main                   5.15.6               hc525480_0    conda-forge
qtkeychain                0.12.0               h51e5271_1    conda-forge
qtwebkit                  5.212                h3383a02_6    conda-forge
qwt                       6.2.0                h1d9fb53_4    conda-forge
readline                  8.1.2                h0f457ee_0    conda-forge
requests                  2.26.0             pyhd8ed1ab_1    conda-forge
requests-oauthlib         1.3.1                    pypi_0    pypi
retrolab                  0.3.21                   pypi_0    pypi
rise                      5.7.1                    pypi_0    pypi
rsa                       4.9                      pypi_0    pypi
ruamel.yaml               0.17.17          py39h3811e60_1    conda-forge
ruamel.yaml.clib          0.2.6            py39h3811e60_0    conda-forge
send2trash                1.8.0              pyhd8ed1ab_0    conda-forge
setuptools                60.0.4           py39hf3d152e_0    conda-forge
simpervisor               0.4                      pypi_0    pypi
sip                       6.6.2            py39h5a03fae_0    conda-forge
six                       1.16.0             pyh6c4a22f_0    conda-forge
snappy                    1.1.9                hbd366e4_1    conda-forge
sniffio                   1.2.0            py39hf3d152e_2    conda-forge
soupsieve                 2.3.2.post1              pypi_0    pypi
sqlalchemy                1.4.29           py39h3811e60_0    conda-forge
sqlite                    3.39.4               h4ff8645_0    conda-forge
statsd                    3.3.0                    pypi_0    pypi
tenacity                  8.1.0              pyhd8ed1ab_0    conda-forge
terminado                 0.12.1           py39hf3d152e_1    conda-forge
testpath                  0.5.0              pyhd8ed1ab_0    conda-forge
tiledb                    2.11.3               h1e4a385_0    conda-forge
tinycss2                  1.1.1                    pypi_0    pypi
tk                        8.6.12               h27826a3_0    conda-forge
toml                      0.10.2             pyhd8ed1ab_0    conda-forge
tomli                     2.0.1              pyhd8ed1ab_0    conda-forge
tornado                   6.1              py39h3811e60_2    conda-forge
tqdm                      4.64.1                   pypi_0    pypi
traitlets                 5.1.1              pyhd8ed1ab_0    conda-forge
typer                     0.6.1                    pypi_0    pypi
typing-extensions         4.4.0                    pypi_0    pypi
tzcode                    2022d                h166bdaf_0    conda-forge
tzdata                    2021e                he74cb21_0    conda-forge
uritemplate               4.1.1                    pypi_0    pypi
urllib3                   1.26.7             pyhd8ed1ab_0    conda-forge
wcwidth                   0.2.5              pyh9f0ad1d_2    conda-forge
webencodings              0.5.1                      py_1    conda-forge
websocket-client          1.2.3              pyhd8ed1ab_0    conda-forge
websockify                0.10.0           py39hb9d737c_2    conda-forge
wheel                     0.37.1             pyhd8ed1ab_0    conda-forge
widgetsnbextension        3.6.1                    pypi_0    pypi
xcb-util                  0.4.0                h516909a_0    conda-forge
xcb-util-image            0.4.0                h166bdaf_0    conda-forge
xcb-util-keysyms          0.4.0                h516909a_0    conda-forge
xcb-util-renderutil       0.3.9                h166bdaf_0    conda-forge
xcb-util-wm               0.4.1                h516909a_0    conda-forge
xerces-c                  3.2.3                h55805fa_5    conda-forge
xorg-kbproto              1.0.7             h14c3975_1002    conda-forge
xorg-libice               1.0.10               h516909a_0    conda-forge
xorg-libsm                1.2.3             hd9c2040_1000    conda-forge
xorg-libx11               1.7.2                h7f98852_0    conda-forge
xorg-libxau               1.0.9                h14c3975_0    conda-forge
xorg-libxdmcp             1.1.3                h516909a_0    conda-forge
xorg-libxext              1.3.4                h7f98852_1    conda-forge
xorg-libxrender           0.9.10            h7f98852_1003    conda-forge
xorg-renderproto          0.11.1            h14c3975_1002    conda-forge
xorg-xextproto            7.3.0             h14c3975_1002    conda-forge
xorg-xproto               7.0.31            h14c3975_1007    conda-forge
xz                        5.2.6                h166bdaf_0    conda-forge
yaml                      0.2.5                h7f98852_2    conda-forge
yarl                      1.8.1                    pypi_0    pypi
zeromq                    4.3.4                h9c3ff4c_1    conda-forge
zipp                      3.6.0              pyhd8ed1ab_0    conda-forge
zlib                      1.2.12               h166bdaf_4    conda-forge
zstd                      1.5.2                h6239696_4    conda-forge
```

### Environment info

```shell
active environment : notebook
    active env location : /srv/conda/envs/notebook
            shell level : 1
       user config file : /home/jovyan/.condarc
 populated config files : /srv/conda/.condarc
          conda version : 4.9.2
    conda-build version : not installed
         python version : 3.8.6.final.0
       virtual packages : __glibc=2.27=0
                          __unix=0=0
                          __archspec=1=x86_64
       base environment : /srv/conda  (writable)
           channel URLs : https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /srv/conda/pkgs
                          /home/jovyan/.conda/pkgs
       envs directories : /srv/conda/envs
                          /home/jovyan/.conda/envs
               platform : linux-64
             user-agent : conda/4.9.2 requests/2.25.0 CPython/3.8.6 Linux/5.10.123+ ubuntu/18.04.6 glibc/2.27
                UID:GID : 1000:1000
             netrc file : None
           offline mode : False
```

**Comment by yuvipanda** [comment] 2022-10-10 20:11
If I install `pyopencl`, the error goes away - but is instead replaced with a error about libGL not being found.

**Comment by yuvipanda** [comment] 2022-10-10 20:18
https://github.com/conda-forge/pygridgen-feedstock/issues/10 is perhaps relevant

**Comment by yuvipanda** [comment] 2022-10-10 20:51
With that, I'm running into problems with it trying to find `libgsl.25`. the gsl from conda-forge only provides libgsl.27.

**Comment by gillins** [comment] 2022-10-10 23:03
@izahn could this be related to your local build picking up different libs?

**Comment by izahn** [comment] 2022-10-10 23:51
> @izahn could this be related to your local build picking up different libs?

Possible, but I can't reproduce the problem. Can you?

**Comment by gillins** [comment] 2022-10-11 00:18
> Possible, but I can't reproduce the problem. Can you?

No I can't. All seems fine in a new environment for me.

@yuvipanda can you install just `qgis` into a new environment and confirm it works?

**Comment by SrNetoChan** [comment] 2022-10-11 08:30
I can't reproduce it either on my linux machines. It seems that @yuvipanda have some mixed channels I see some packages from pypi in his list. So definitely try to install qgis in a clean enviornment.

**Comment by ocefpaf** [comment] 2022-10-11 14:13
Probably not related to the `pypi` packages but I bet @yuvipanda is trying to run that in a docker image and some X11 stuff, that we expected to exist on users machine, is missing. I'll investigate and see what would be the best fix, apt-install them or conda install if we have them.

**Comment by ocefpaf** [comment] 2022-10-11 14:39
@yuvipanda can you try to yum install `mesa-libGL` or the equivalent on your docker image? These are always present in user environments and are not supposed to be installed by conda. Note that you may need to set a `DISPLAY` too.

**Comment by yuvipanda** [comment] 2022-10-11 14:59
Yep, that's right - it was in a docker image. https://github.com/berkeley-dsep-infra/datahub/tree/staging/deployments/cee/image has the config! I installed `libgl1-mesa-glx` which is the equivalent and that fixed the issue for GL. I think the conda related issues would be:

1. Why does it want the wrong version of libgsl? libgsl is coming from conda, not apt
2. What is the deal with OpenCL?

I think getting `libgl1-mesa-glx` from apt makes sense for docker for reasons outlined in https://github.com/conda-forge/pygridgen-feedstock/issues/10.

**Comment by ocefpaf** [comment] 2022-10-11 15:27
> * Why does it want the wrong version of libgsl? libgsl is coming from conda, not apt
> * What is the deal with OpenCL?

No idea. I could not reproduce these two locally. That may be due to our new Linux build\* or it may be just some some oddities due to the docker image. However, those are not expected to be in the user system, like libgl, those should be conda installed (if they are really missing but their linkage may be at question*\).

**Comment by yuvipanda** [comment] 2022-10-11 16:07
I'll try make a reproducible minimal example shortly. 

> However, those are not expected to be in the user system, like libgl, those should be conda installed (if they are really missing but their linkage may be at question*).

If I'm reading this correctly, both OpenCL and gsl should be installed by conda, right?

**Comment by izahn** [comment] 2022-10-11 16:24
> > * Why does it want the wrong version of libgsl? libgsl is coming from conda, not apt

Because you have installed `gsl 2.7.1` from the `defaults` channel instead of from the `conda-forge` channel. Mixing `defaults` and `conda-forge` is not recommended and is known to cause things to break.

> > * What is the deal with OpenCL?

Not sure about this one, the opencl situation seem complicated in general.

**Comment by yuvipanda** [comment] 2022-10-11 16:38
@izahn oooh, I completely missed the mixing! I have no idea how *that* happened, given I explicitly say 'conda-forge' in https://github.com/berkeley-dsep-infra/datahub/blob/staging/deployments/cee/image/environment.yml#L2. I'll try make a reproducible example and see.

**Comment by ocefpaf** [comment] 2022-10-11 16:44
> @izahn oooh, I completely missed the mixing!

Oops. I missed that too! Sorry @izahn!

> have no idea how _that_ happened, given I explicitly say 'conda-forge'

That doesn't matter for conda if your local `.condarc` has defaults in it. In our docs we recommend a `.condarc` with only conda-forge and strict channel enabled.

```
channel_priority: strict
channels:
  - conda-forge
```

**Comment by SrNetoChan** [comment] 2023-01-22 19:08
Can we close this one?

**Comment by SrNetoChan** [comment] 2023-06-25 12:25
I have just realized that several builds including 3.28.x aren't able to find OpenCL and disables it's support. So something must be wrong

**Closed** 2023-07-04 10:00 UTC
Labels: bug, Wait feedback
